### ISSUE TITLE
Stock ticker Node.js

### ISSUE THREAD

**Issue by malicolm** [ari-goldman/team4-group-project#8]
Create api endpoint to get information from notable stocks, Blue chip, s&p 500, NASDAQ, etc.

**Comment by princetomar** [comment]
Step 1: Choose an API provider to get stock data. Some popular providers are Alpha Vantage, Yahoo Finance, and Finnhub. For this example, we will use Alpha Vantage.

Install the necessary packages for making HTTP requests and parsing JSON data. You can use the axios package for making HTTP requests and body-parser for parsing JSON data. Run the following command in your terminal to install these packages:

npm install axios body-parser

Step 2: Create a new file called server.js and import the necessary packages: 

const express = require('express');
const axios = require('axios');
const bodyParser = require('body-parser');

const app = express();
const port = 3000;

app.use(bodyParser.json());

Step 3: Define a route for getting stock data. In this example, we will define a route for getting the current stock price of a specified symbol:

app.get('/stocks/:symbol', async (req, res) => {
  const symbol = req.params.symbol;
  const apiKey = 'YOUR_API_KEY'; // replace with your Alpha Vantage API key

  try {
    const response = await axios.get(`https://www.alphavantage.co/query?function=GLOBAL_QUOTE&symbol=${symbol}&apikey=${apiKey}`);

    const stockData = response.data['Global Quote'];
    const price = parseFloat(stockData['05. price']);

    res.json({ symbol, price });
  } catch (error) {
    console.error(error);
    res.status(500).send('Error getting stock data');
  }
});

This route uses the Alpha Vantage API to get the current stock price of the specified symbol. The route expects a parameter called symbol in the URL (e.g. /stocks/AAPL), and it returns a JSON object with the symbol and price.


Step 5: Start the server by listening on the specified port:

app.listen(port, () => {
  console.log(`Server listening on port ${port}`);
});

Step 6: Replace the YOUR_API_KEY placeholder with your actual API key from Alpha Vantage.

Step 7: Run the server by running the following command in your terminal:

node server.js
